### ISSUE TITLE
Use i64 instead of f64

### ISSUE THREAD

**Issue by otavio** [Mnwa/ms#1]
This would allow for easier use with `chrono`.

**Comment by Mnwa** [comment]
Hey! It is are good idea, but how to parse dates with decimal values? Like are `2.5h`

**Comment by otavio** [comment]
> Hey! It is are good idea, but how to parse dates with decimal values? Like are `2.5h`

I am suggesting to use the return as i64. As it will return as milliseconds, it won't use fractions.
