### ISSUE TITLE
Perhaps return std::time::Duration rather than i64?

### ISSUE THREAD

**Issue by JoshMcguigan** [Mnwa/ms#3]
Hi, thanks for your work on this library.

The standard library includes `std::time::Duration` as a type safe way of passing around time durations. Have you considered returning that type rather than an i64?

**Comment by Mnwa** [comment]
Hey! `i64` can easily be converted into `std::time::Duration` and `chrono::Duration`. Today I don't want to change this, but maybe later.

**Comment by otavio** [comment]
For `std::time::Duration` you can use `parse_duration` crate. I moved from it to `ms` as it avoids one layer and for my use, it makes more sense.

Also, it has fewer dependencies and for me it is important.
