### ISSUE TITLE
Is the reverse possible?

### ISSUE THREAD

**Issue by rakshith-ravi** [Mnwa/ms#4]
Hey!

Thank you for this library. It's quite useful.

I was wondering if the reverse of what this library does is possible? That is, given a `u64` representing milliseconds, can we get the human-readable version of it?

**Comment by Mnwa** [comment]
Hi! I think it's possible and I'll do it soon

**Comment by rakshith-ravi** [comment]
Great. Thanks a ton! :D

**Comment by rakshith-ravi** [comment]
I don't know if this will be helpful, perhaps you have a different way of doing it, but currently I'm doing this. Hope it helps:

```rust


fn get_duration(mut duration: u64) -> String {
	// If less than 1 second, print the ms
	if (duration / 1000) <= 0 {
		return format!("{}ms", duration);
	}
	duration = duration / 1000; // Seconds

	// If less than 60 seconds, print the seconds
	if (duration / 60) <= 0 {
		return format!("{}s", duration);
	}
	duration = duration / 60; // Minutes

	// If less than 60 minutes, print the minutes
	if (duration / 60) <= 0 {
		return format!("{}m", duration);
	}
	duration = duration / 60; // Hours

	// If less than 24 hours, print the hours
	if (duration / 24) <= 0 {
		return format!("{}h", duration);
	}
	duration = duration / 24; // Days

	// If less than 7 days, print the days
	if (duration / 7) <= 0 {
		return format!("{}d", duration);
	}
	duration = duration; // Days

	// If less than 30 days, print the weeks
	if (duration / 30) <= 0 {
		return format!("{}w", duration / 7);
	}
	duration = duration / 30; // Months

	// If less than 12 months, print the months
	if (duration / 12) <= 0 {
		return format!("{}M", duration);
	}
	duration = duration / 12; // Years

	// Neither of those works, print the number of years
	return format!("{}y", duration);
}
```

**Comment by Mnwa** [comment]
@rakshith-ravi you can check the PR version [here](https://github.com/Mnwa/ms/pull/5). It's what are you want?

**Comment by Mnwa** [comment]
Function named `from_ms`

**Comment by rakshith-ravi** [comment]
Something like this, yes, but more specifically, given milliseconds, it should be able to automatically figure out the postfix.

For example, if we give `61000` as the input, it should automatically output `1m`, realizing that it's a minute. So we can automatically detect the postfix.

**Comment by Mnwa** [comment]
But what it will be a must to print when we pass
```get_duration(10 * DAY as i64)```? `1w` or `10d`?

**Comment by rakshith-ravi** [comment]
Well, with the algorithm I gave in the previous post, it would print 1w. But I guess that doesn't make sense since 10d is more accurate. I'm not sure what the right approach is. Open to suggestions.

Basically this is coming from a use-case of CLIs where the application shows how long it's been running. So instead of saying the uptime is `123456789` ms, I figured it'd be easier to say `2w` or something like that.

**Comment by Mnwa** [comment]
May be limit `get_duration` to days? Only ms, secs, mins, hours, and days?

**Comment by rakshith-ravi** [comment]
Sure. Is there a way to override with some kind of a flag parameter?

**Comment by Mnwa** [comment]
At the start, I think not. May be a letter if someone needs it, I'll create a new function without limitations.

**Comment by rakshith-ravi** [comment]
Got it. Makes sense

**Comment by Mnwa** [comment]
So, you can check the method `get_max_possible_duration` on the same PR

**Comment by rakshith-ravi** [comment]
Yes, that looks great. Thank you so much for this! :D

**Comment by Mnwa** [comment]
Great! You can use 1.3.0 version now with Cargo
